version: "3"

services:
        web:
          container_name: apirestnodemongo
          restart: always
          build: .
          ports:
              - "4000:4000"
          links: 
              - mongo
          volumes: 
              - .:/usr/src/app
        mongo:
          container_name: mongodatabase
          image: mongo
          ports: 
              - "27018:27017"
          logging: 
              driver: none